### PR TITLE
LPS-111127 Depot Languages - test

### PR DESCRIPTION
**Pull request by boton**

### CODE REVIEW

**Comment by boton** [comment]
ci:test:sf

**Comment by boton** [comment]
ci:test:relevant

**Comment by boton** [comment]
ci:stop

**Comment by boton** [comment]
esta fallando el sf y no se porque ¯\_(ツ)_/¯ si mañana sigue investigo más

**Comment by boton** [comment]
ci:test:sf

**Comment by boton** [comment]
ci:test:sf

**Comment by boton** [comment]
ci:test:relevant

**Comment by ambrinchaudhary** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ambrinchaudhary** [comment]
Pull request submitted to https://github.com/ambrinchaudhary/liferay-portal/pull/335. [See changes here.](https://github.com/ambrinchaudhary/liferay-portal/compare/fdca7ec~2...fdca7ec) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ambrinchaudhary** [comment]
Pull request submitted to https://github.com/ambrinchaudhary/liferay-portal/pull/336. [See changes here.](https://github.com/ambrinchaudhary/liferay-portal/compare/ec13e31~2...ec13e31) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
