### PR TITLE
LPS-110020 Replace AlloyEditor in Title in Wiki

### PR DESCRIPTION
**Pull request by julien**

### CODE REVIEW

**Comment by julien** [comment]
ci:test:sf

**Comment by julien** [comment]
ci:test:stable

**Comment by ambrinchaudhary** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ambrinchaudhary** [comment]
Pull request submitted to https://github.com/austinchiang/liferay-portal/pull/742. [See changes here.](https://github.com/ambrinchaudhary/liferay-portal/compare/a344d2c~3...a344d2c) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
