### PR TITLE
LPS-69240 Sending the urlTitle every time the interval tries to save the blog entry

### PR DESCRIPTION
**Pull request by 4lejandrito**

### CODE REVIEW

**Comment by 4lejandrito** [comment]
ci:retest

**Comment by ambrinchaudhary** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ambrinchaudhary** [comment]
Pull request submitted to https://github.com/ambrinchaudhary/liferay-portal/pull/115. [See changes here.](https://github.com/ambrinchaudhary/liferay-portal/compare/08d3c99~5...08d3c99) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ambrinchaudhary** [comment]
Pull request submitted to https://github.com/adolfopa/liferay-portal/pull/404. [See changes here.](https://github.com/ambrinchaudhary/liferay-portal/compare/16c6194~4...16c6194) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
