### PR TITLE
LPS-67414 Add padding around multiple upload component

### PR DESCRIPTION
**Pull request by adolfopa**

### CODE REVIEW

**Comment by ambrinchaudhary** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by adolfopa** [comment]
Hey @jwu910 @jonmak08

Is the LPS right? After applying these changes the bug is still reproducible. Also, it looks like none of the pulls modify D&M multiple upload comments.

**Comment by jonmak08** [comment]
Hey @adolfopa and @ambrinchaudhary,

While fixing the D&M multiple uploader, we found additional areas that needed to be addressed with the same/similar change as well.  We split those into different pull requests since they are for different components and thus go to different leads to review.

We sent 2 more additional changes to @pat270 (https://github.com/pat270/liferay-portal/pull/201, https://github.com/pat270/liferay-portal/pull/202).

Please let me know if you have any questions. Thanks!

**Comment by jonmak08** [comment]
Hey @adolfopa,

The pull request to @robertoDiaz for the multiple uploader being too close can be found at https://github.com/robertoDiaz/liferay-portal/pull/570.

Please let me know if you have any questions. Thanks!

**Comment by ambrinchaudhary** [comment]
Hey @jonmak08, 
then if I am not wrong, this fix is for social activity (not for DM which is the one addressed in the LPS, and this one has been sent to @robertoDiaz). I will create a new LPS for it and rename the commits. 
I would suggest you to do the same with the PR's that Patrick have (for Open Social and License Manager portlet), because they are not for DM either. We can link all this LPS as related and track each of them easily. Otherwhise, there should be a unique LPS in Jira with all this changes.

**Comment by jonmak08** [comment]
Hey @ambrinchaudhary,

We have already pushed the changes that went to @pat270 into upstream (https://github.com/liferay/liferay-portal/compare/5382f7284c1bab2ece4c51fad01d4beed2373f58...0238a85abe52a720ecc26da6d04ba9eb0ff44ded).  I should have created new tickets, but in the haste of time and fixing other issues, I just used the same ticket numbers.

I realize where I messed up with all the pulls.  The social activity changes should have been sent to @robertoDiaz while the collaboration ones should have been sent to you (https://github.com/robertoDiaz/liferay-portal/pull/570).

I will resend the one currently in @robertoDiaz's queue to you.

Please let me know if you have any questions. Thanks!

**Comment by ambrinchaudhary** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ambrinchaudhary** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/49809. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
