### PR TITLE
LPS-109997 Replace Alloy Editor with Aui input

### PR DESCRIPTION
**Pull request by julien**

### CODE REVIEW

**Comment by julien** [comment]
ci:test:sf

**Comment by julien** [comment]
ci:test:stable

**Comment by ambrinchaudhary** [comment]
Closing, this changes have been sent in https://github.com/ambrinchaudhary/liferay-portal/pull/324

**Comment by ambrinchaudhary** [comment]
Pull request submitted to https://github.com/liferay-lima/liferay-portal/pull/316. [See changes here.](https://github.com/ambrinchaudhary/liferay-portal/compare/c5cb6c72ab09~3...c5cb6c72ab09)

**Pull request closed without merging**
