### PR TITLE
LPS-83968 Use liferay-npm-bundler-preset-liferay-dev

### PR DESCRIPTION
**Pull request by boton**

### CODE REVIEW

**Comment by ambrinchaudhary** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by 4lejandrito** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ambrinchaudhary** [comment]
new PR https://github.com/ambrinchaudhary/liferay-portal/pull/181

**Pull request closed without merging**
