### PR TITLE
LPS-110015 Replace AlloyEditor in Content field in Knowledge Base Templates

### PR DESCRIPTION
**Pull request by julien**

### CODE REVIEW

**Comment by julien** [comment]
ci:test:sf

**Comment by julien** [comment]
ci:test:stable

**Comment by ambrinchaudhary** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ambrinchaudhary** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/86479. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
