### PR TITLE
LPS-74547 Use the corrent folder as the default target

### PR DESCRIPTION
**Pull request by sergiogonzalez**

### CODE REVIEW

**Comment by ambrinchaudhary** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by IstvanD** [comment]
Hello @ambrinchaudhary 

I was wondering if you could find time to review the pull request.

Please let me know if you need any help.

Thank you,
István

**Comment by ambrinchaudhary** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/51654. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ambrinchaudhary** [comment]
Sorry for the delay @IstvanD, we wanted to be sure this wouldn't affect the drag/drop option

**Comment by IstvanD** [comment]
No worries @ambrinchaudhary, thank you for dealing with the pull and forwarding it.

**Pull request closed without merging**
