### PR TITLE
[See description] LPS-69814 Only allow supported file types

### PR DESCRIPTION
**Pull request by sergiogonzalez**
* Check the consistency of the messages (blogs and url tabs seems to have different messages)
* See if we need to introduce more information about the type of files that can be uploaded so the user doesn't make the error and he knows it in advance.

### CODE REVIEW

**Comment by sergiogonzalez** [comment]
cc/ @pavel-savinov

**Comment by ambrinchaudhary** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ambrinchaudhary** [comment]
Pull request submitted to https://github.com/sergiogonzalez/liferay-portal/pull/3715. [See changes here.](https://github.com/ambrinchaudhary/liferay-portal/compare/7015e26~3...7015e26) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ambrinchaudhary** [comment]
Pull request submitted to https://github.com/sergiogonzalez/liferay-portal/pull/3720. [See changes here.](https://github.com/ambrinchaudhary/liferay-portal/compare/9cd21bd~6...9cd21bd) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ambrinchaudhary** [comment]
Pull request submitted to https://github.com/liferay-lima/liferay-portal/pull/136.

**Pull request closed without merging**
