### PR TITLE
LPS-114255 Fix the video resizer plugin for ckeditor

### PR DESCRIPTION
**Pull request by julien**
These changes fix the video resizer plugin for CKEditor.

Apart from some cleaning like removing unnecessary variables, the fix for video resizing can be seen [here](https://github.com/ambrinchaudhary/liferay-portal/compare/master...julien:LPS-114255#diff-0adbb83f228e3855a8d047a5c65375a9), instead of using percentages to style the widget element's width we now use pixels .

### CODE REVIEW

**Comment by julien** [comment]
ci:test:sf

**Comment by julien** [comment]
ci:test:relevant

**Comment by ambrinchaudhary** [comment]
Pull request forwarded to https://github.com/liferay-lima/liferay-portal/pull/151. [See changes here.](https://github.com/ambrinchaudhary/liferay-portal/compare/7e5b2db19d37~4...7e5b2db19d37)

**Comment by julien** [comment]
ci:stop

**Comment by julien** [comment]
ci:close

**Pull request closed without merging**
