### PR TITLE
LPS-110363 Use var for animation duration

### PR DESCRIPTION
**Pull request by boton**

### CODE REVIEW

**Comment by boton** [comment]
ci:test:sf

**Comment by boton** [comment]
ci:test:relevant

**Comment by boton** [comment]
ci:test:relevant

**Comment by ambrinchaudhary** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ambrinchaudhary** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/86601. [See changes here.](https://github.com/ambrinchaudhary/liferay-portal/compare/33c45c8~1...33c45c8) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ambrinchaudhary** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/86603. [See changes here.](https://github.com/ambrinchaudhary/liferay-portal/compare/1414770~1...1414770) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ambrinchaudhary** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/86604. [See changes here.](https://github.com/ambrinchaudhary/liferay-portal/compare/4cec290~2...4cec290) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
