### PR TITLE
LPS-102559 Contain wrapper in component file

### PR DESCRIPTION
**Pull request by jbalsas**

### CODE REVIEW

**Comment by markocikos** [comment]
@ambrinchaudhary As @boton commented [here](https://github.com/boton/liferay-portal/pull/95#issuecomment-542797917) and [here](https://github.com/wincent/liferay-portal/pull/73#discussion_r335035639), buttons now contain `btn-primary` css class, added by default. This does not change anything visually, as the styles are overridden by `btn-floating-bar` styles.

We can remove the `btn-primary` class by setting `displayType={falsy value}`, but that looks to me a bit hacky. Maybe the best way is to leave default behavior as it is, and suggest to the Clay guys to add an option like `displayType='none'`. Or we can embrace the idea that there needs to be a display type, that can be overridden for specific implementation, like in this solution. What do you think?

**Comment by ambrinchaudhary** [comment]
Just started reviewing :)

**Comment by ambrinchaudhary** [comment]
Hey @markocikos, as this `btn-primary` does not have any visual impact for now, I will send the PR and we can discuss with Clay any option to avoid this default class (I agree that `displayType='none'`could be the best solution). I will chek this with @boton once he is back from holidays.

**Comment by ambrinchaudhary** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/79761. [See changes here.](https://github.com/ambrinchaudhary/liferay-portal/compare/be201310337b~1...be201310337b)

**Comment by ambrinchaudhary** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/79797. [See changes here.](https://github.com/ambrinchaudhary/liferay-portal/compare/ee29441~1...ee29441) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ambrinchaudhary** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/79798. [See changes here.](https://github.com/ambrinchaudhary/liferay-portal/compare/d2edf77~2...d2edf77) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
