### PR TITLE
LPS-111225 - Replace <liferay-ui:input-editor> with  <liferay-editor:editor> in announcements-web

### PR DESCRIPTION
**Pull request by julien**
The goal of this change is to replace `<liferay-ui:input-editor>`
(which was deprecated in 7.1.0) with `<liferay-editor:editor>`.

A previous Jira ticket (https://issues.liferay.com/browse/LPS-109998)
and pull request (#313)
are currently in review and change the same files, so the commit
`a65f2a40ed696fe9a2ba5673604bf86d3d884e5a` has been cherry picked on this
branch to avoid confusion.

### CODE REVIEW

**Comment by julien** [comment]
ci:test:sf

**Comment by julien** [comment]
ci:test:stable

**Comment by julien** [comment]
ci:test:relevant

**Comment by ambrinchaudhary** [comment]
Hi @julien, 

I guess this pull replaces https://github.com/ambrinchaudhary/liferay-portal/pull/313/ and https://github.com/ambrinchaudhary/liferay-portal/pull/311/, am I right?

**Comment by julien** [comment]
Hi @ambrinchaudhary, 

In this PR we're just changing `<liferay-ui:input-editor>` with `<liferay-editor:editor>`, and as I wrote in my commit message, I cherry-picked [`a65f2a40ed696fe9a2ba5673604bf86d3d884e5a`](https://github.com/ambrinchaudhary/liferay-portal/pull/313/commits/a65f2a40ed696fe9a2ba5673604bf86d3d884e5a) so it should have all the required changes but please double check.

**Comment by julien** [comment]
ci:test:relevant

**Comment by ambrinchaudhary** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ambrinchaudhary** [comment]
Pull request submitted to https://github.com/austinchiang/liferay-portal/pull/745. [See changes here.](https://github.com/ambrinchaudhary/liferay-portal/compare/5e7fa5c~3...5e7fa5c) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
