### PR TITLE
LPS-69814 Simplify

### PR DESCRIPTION
**Pull request by sergiogonzalez**

### CODE REVIEW

**Comment by ambrinchaudhary** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by sergiogonzalez** [comment]
ci:reopen

**Comment by ambrinchaudhary** [comment]
Pull request submitted to https://github.com/sergiogonzalez/liferay-portal/pull/3738. [See changes here.](https://github.com/ambrinchaudhary/liferay-portal/compare/53551e6~1...53551e6) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ambrinchaudhary** [comment]
Pull request submitted to https://github.com/marcoscv-work/liferay-portal/pull/333. [See changes here.](https://github.com/ambrinchaudhary/liferay-portal/compare/39443090589f~1...39443090589f)

**Pull request closed without merging**
