### PR TITLE
LPS-41934

### PR DESCRIPTION
**Pull request by adolfopa**

### CODE REVIEW

**Comment by adolfopa** [comment]
Here it is @jbalsas, you can stop hating me ;-)

**Comment by jbalsas** [comment]
Thanks @adolfopa!! 😘

**Comment by ambrinchaudhary** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ambrinchaudhary** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/50224. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
