### PR TITLE
LPS-68414 Updates Stumbleupon Badge

### PR DESCRIPTION
**Pull request by fernandosouza**

### CODE REVIEW

**Comment by ambrinchaudhary** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by fernandosouza** [comment]
Hello, @ambrinchaudhary. This error that C.I has found is a Linkedin button internal error. I'm trying to find out a way to prevent it.

**Comment by fernandosouza** [comment]
ci:reopen

**Comment by fernandosouza** [comment]
ci:retest

**Comment by fernandosouza** [comment]
@ambrinchaudhary, branch updated.

**Comment by ambrinchaudhary** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by fernandosouza** [comment]
ci:retest

**Comment by fernandosouza** [comment]
ci:stop

**Comment by fernandosouza** [comment]
ci:retest

**Comment by fernandosouza** [comment]
ci:retest

**Comment by fernandosouza** [comment]
Hi, @ambrinchaudhary. The branch is updated. Waiting for CI.

**Comment by fernandosouza** [comment]
ci:reopen

**Comment by ambrinchaudhary** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ambrinchaudhary** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/46949. [See changes here.](https://github.com/ambrinchaudhary/liferay-portal/compare/f553593~2...f553593) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
