### PR TITLE
LPS-103656 Don't set minimum since maximum will appear when clicking the down key

### PR DESCRIPTION
**Pull request by adolfopa**

### CODE REVIEW

**Comment by ambrinchaudhary** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ambrinchaudhary** [comment]
Just started reviewing :)

**Comment by ambrinchaudhary** [comment]
Hey @adolfopa, 
if we remove the "min" attribute, in the calendar you can select previous dates, which is not what we want. Additionally, this gives you a visual help by having those dates disabled. If terms of UX I found it more usefull and I don't think we want to remove it. So we may need to found another solution to fix this bug. 
Screenshot 2019-11-07 at 14 33 46

**Comment by adolfopa** [comment]
@knchau See @ambrinchaudhary 's comments; we need an alternative fix that keeps the min year around.

**Comment by knchau** [comment]
Hi @ambrinchaudhary,

Even if we chose a previous date, an error message would be displayed that states "Please enter an expiration date that comes after today" when trying to save so it isn't completely removed. I've only removed the minimum on the calendar picker, would you still want to look for an alternative fix? Thanks!

**Comment by ambrinchaudhary** [comment]
Hey @knchau, sorry I missed your comment. 
Yes, I would look for an other solution. Otherwise, I will close this bug as won't fix, because setting the "min" adds more value that deleting it. In both cases, an error is displayed informing that the date is not valid.

**Pull request closed without merging**
