### PR TITLE
LPS-111251 Replace <liferay-ui:input-editor> with  <liferay-editor:editor> in wiki-engine-input-editor-common

### PR DESCRIPTION
**Pull request by julien**
The goal of this change is to replace `<liferay-ui:input-editor>`
(which was deprecated in 7.1.0) with `<liferay-editor:editor>`.

A previous Jira ticket (https://issues.liferay.com/browse/LPS-110019)
and pull request (#315) are currently in review and change the same
files, so the commits on the previous PR (#315) have been cherry picked on
this branch to avoid confusion.

@ambrinchaudhary you can close #315 and check this one instead

Thanks!

### CODE REVIEW

**Comment by julien** [comment]
ci:test:sf

**Comment by julien** [comment]
ci:test:stable

**Comment by julien** [comment]
ci:test:relevant

**Comment by julien** [comment]
Hi @john-co, 

Could you please check this when you have time? 

For more context, in this [02fd6756ad35a685ecbba66ead60428527c3a178](https://github.com/ambrinchaudhary/liferay-portal/pull/326/commits/02fd6756ad35a685ecbba66ead60428527c3a178) our intent is to replace `<liferay-ui:input-editor>` (which was deprecated in 7.1.0) with `<liferay-editor:editor>`, and we're not able to see if `ci:test:relevant` is failing because of this.

Thanks!

**Comment by john-co** [comment]
ci:test:bundle

**Comment by john-co** [comment]
Testray Results Comparison:
https://testray.liferay.com/home/-/testray/runs/compare?compare=true&view=details&statusA=3&testrayRunIdB=1084950765&testrayRunIdA=1084889838&statusB=2

- [Related] - all failing tests except for CPWiki#CKEditorSmoke - test fix?, will verify manually
error: ```Element is not present at "//div[contains(@class,'cke_editable_inline') and contains(@id,'_content')]"```
- [Related] - CPWiki#CKEditorSmoke - looks like <p> tags are displayed after publishing the wiki - will manually verify
image

**Comment by john-co** [comment]
Currently working on test fixes for ckeditor change

/cc @austinchiang

**Comment by ambrinchaudhary** [comment]
> itor change
> 
> /cc @austinchiang

Once I review this PR I will send it to Austin so he can fix the tests. Thanks!

**Comment by john-co** [comment]
Thanks @ambrinchaudhary, 
fwiw, I sent my wip test fixes to @austinchiang https://github.com/austinchiang/liferay-portal/pull/739

**Comment by ambrinchaudhary** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ambrinchaudhary** [comment]
Pull request submitted to https://github.com/austinchiang/liferay-portal/pull/743. [See changes here.](https://github.com/ambrinchaudhary/liferay-portal/compare/1bbc57f~4...1bbc57f) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
