### PR TITLE
LPS-110014 Replace AlloyEditor in Title field in Knowledge Base Templates

### PR DESCRIPTION
**Pull request by julien**

### CODE REVIEW

**Comment by julien** [comment]
ci:test:sf

**Comment by julien** [comment]
ci:test:stable

**Comment by ambrinchaudhary** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ambrinchaudhary** [comment]
Pull request submitted to https://github.com/austinchiang/liferay-portal/pull/712. [See changes here.](https://github.com/ambrinchaudhary/liferay-portal/compare/3e3d7dd~2...3e3d7dd) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ambrinchaudhary** [comment]
Pull request submitted to https://github.com/austinchiang/liferay-portal/pull/715. [See changes here.](https://github.com/ambrinchaudhary/liferay-portal/compare/0978ec1~3...0978ec1) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ambrinchaudhary** [comment]
Pull request submitted to https://github.com/ambrinchaudhary/liferay-portal/pull/321. [See changes here.](https://github.com/ambrinchaudhary/liferay-portal/compare/ec3a8ad~7...ec3a8ad) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ambrinchaudhary** [comment]
Pull request submitted to https://github.com/austinchiang/liferay-portal/pull/723. [See changes here.](https://github.com/ambrinchaudhary/liferay-portal/compare/929fd7f~8...929fd7f) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
