### PR TITLE
LPS-84119

### PR DESCRIPTION
**Pull request by hhuijser**

### CODE REVIEW

**Comment by hhuijser** [comment]
Hey @ambrinchaudhary 

I added some logic to SourceFormatter to deal with *.soy
Would you mind having a look at my commits to see if I am not overdoing stuff and breaking logic (as I am not too familiar with soy)?

Thanks!

**Comment by ambrinchaudhary** [comment]
Thanks @hhuijser , thanks for sending this... I will test my components and ask other teams to do the same.

**Comment by ambrinchaudhary** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ambrinchaudhary** [comment]
Pull request submitted to https://github.com/p2kmgcl/liferay-portal/pull/371. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
