### PR TITLE
LPS-72803 Avoid add the protocol and the domain when returning the title

### PR DESCRIPTION
**Pull request by robertoDiaz**

### CODE REVIEW

**Comment by robertoDiaz** [comment]
ci:retest

**Comment by robertoDiaz** [comment]
@ambrinchaudhary 

Los tests rotos parecen que no están relacionados con la pull. 👍

**Comment by ambrinchaudhary** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ambrinchaudhary** [comment]
Pull request submitted to https://github.com/adolfopa/liferay-portal/pull/569. [See changes here.](https://github.com/ambrinchaudhary/liferay-portal/compare/c1fe2f7~2...c1fe2f7) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ambrinchaudhary** [comment]
Pull request submitted to https://github.com/adolfopa/liferay-portal/pull/573. [See changes here.](https://github.com/ambrinchaudhary/liferay-portal/compare/6c01261~4...6c01261) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
