### PR TITLE
LPS-88324 UserPortrait taglib

### PR DESCRIPTION
**Pull request by adolfopa**

### CODE REVIEW

**Comment by adolfopa** [comment]
ci:test:sf

**Comment by adolfopa** [comment]
ci:test:relevant

**Comment by ambrinchaudhary** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ambrinchaudhary** [comment]
Pull request submitted to https://github.com/patriciajeanperez/liferay-portal/pull/134. [See changes here.](https://github.com/ambrinchaudhary/liferay-portal/compare/4e72d38~1...4e72d38) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ambrinchaudhary** [comment]
Pull request submitted to https://github.com/austinchiang/liferay-portal/pull/345. [See changes here.](https://github.com/ambrinchaudhary/liferay-portal/compare/e76d540~1...e76d540) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
