### PR TITLE
LPS-41934 Configures itemselector as file picker in tinymce

### PR DESCRIPTION
**Pull request by jbalsas**

### CODE REVIEW

**Comment by jbalsas** [comment]
ci:retest

**Comment by jbalsas** [comment]
ci:retest

**Comment by ambrinchaudhary** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ambrinchaudhary** [comment]
Pull request submitted to https://github.com/adolfopa/liferay-portal/pull/607. [See changes here.](https://github.com/ambrinchaudhary/liferay-portal/compare/ed1981b~1...ed1981b) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
