### PR TITLE
LPS-110007 Fix autoSize functionality

### PR DESCRIPTION
**Pull request by julien**

### CODE REVIEW

**Comment by julien** [comment]
ci:test:sf

**Comment by julien** [comment]
ci:test:stable

**Comment by julien** [comment]
```
[java] 1: Function 'AutoSize' much match pattern '^[a-z0-9][_a-zA-Z0-9]*$': ./portal-web/docroot/html/taglib/aui/input/page.jsp 363 (SourceCheck:JSPFunctionNameCheck)
```

That's a bit disappointing because in this case it's a constructor function :crying_cat_face:

**Comment by julien** [comment]
ci:test:sf

**Comment by ambrinchaudhary** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ambrinchaudhary** [comment]
Pull request submitted to https://github.com/julien/liferay-portal/pull/239. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by julien** [comment]
Just to reflect what on Slack:
Everything's OK in terms of functionality and behaviour according to @ambrinchaudhary (who will correct me if I'm wrong). Ideally we're going to move this to a module, so that we can separate the (s)css from the JS and use es6, so I'll take care of that since we still have some before we can send this.

**Pull request closed without merging**
