### PR TITLE
[TECHNICAL-SUPPORT] LPS-69693 Disable heading text formatting in Wiki editor for Creole

### PR DESCRIPTION
**Pull request by robertoDiaz**
Hey @robertoDiaz 

I'm resending https://github.com/robertoDiaz/liferay-portal/pull/513

Message of https://github.com/robertoDiaz/liferay-portal/pull/513 : 

Unfortunately, [LPS-69693](https://issues.liferay.com/browse/LPS-69693) was incomplete, and I had to extend it with an additional use case.
Please see [LPS-69693](https://issues.liferay.com/browse/LPS-69693) for details.

Thank you!

Best regards,
István

### CODE REVIEW

**Comment by IstvanD** [comment]
Hey @ambrinchaudhary 

I was wondering if you could find the time to review the pull.
Please let me know you have questions about the fix.

Thank you!

Best regards,
István

**Comment by ambrinchaudhary** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ambrinchaudhary** [comment]
Hey @IstvanD, 
sorry for the delay. I will try to review it tomorrow. 
Regards.

**Comment by ambrinchaudhary** [comment]
Sent to Brian: https://github.com/brianchandotcom/liferay-portal/pull/46673

**Pull request closed without merging**
