### PR TITLE
LPS-109249 Add test to check inputs values

### PR DESCRIPTION
**Pull request by boton**

### CODE REVIEW

**Comment by boton** [comment]
ci:tes:sf

**Comment by boton** [comment]
ci:test:relevant

**Comment by boton** [comment]
ci:test:sf

**Comment by ambrinchaudhary** [comment]
Pull request submitted to https://github.com/boton/liferay-portal/pull/138. [See changes here.](https://github.com/ambrinchaudhary/liferay-portal/compare/58b5059909d0~1...58b5059909d0)

**Pull request closed without merging**
