### PR TITLE
LPS-68180 SF

### PR DESCRIPTION
**Pull request by csierra**
/cc @topolik Test is not passing because antisamy formats the output in a different way than the test expects

### CODE REVIEW

**Comment by csierra** [comment]
ci:stop

**Comment by csierra** [comment]
hey @ambrinchaudhary @topolik, I had to establish a new `<allowed-empty-tags>` section to correctly process the new code that @ambrinchaudhary sent me:
`<p><picture><source media="(max-width:400px)" srcset="/o/adaptive-media/image/39512/12345/IMG_6661.jpg" /><source media="(max-width:1200px) and (min-width:400px)" srcset="/o/adaptive-media/image/39512/12346/IMG_6661.jpg" /><source media="(max-width:2400px) and (min-width:1200px)" srcset="/o/adaptive-media/image/39512/123467/IMG_6661.jpg" /></picture></p>`

I don't know why it was not needed until now... is it correct @topolik?

I also accepted the `-` in the mimetype regexp as @topolik pointed out. 

Bests.

**Comment by ambrinchaudhary** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ambrinchaudhary** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/43470. [See changes here.](https://github.com/ambrinchaudhary/liferay-portal/compare/60bf7c8~1...60bf7c8) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
