### PR TITLE
LPS-68326 Enable testing through npm caching mechanism

### PR DESCRIPTION
**Pull request by ambrinchaudhary**

### CODE REVIEW

**Comment by ambrinchaudhary** [comment]
ci:retest

**Comment by ambrinchaudhary** [comment]
ci:retest

**Comment by carloslancha** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ambrinchaudhary** [comment]
ci:retest

**Comment by ambrinchaudhary** [comment]
ci:retest

**Comment by ambrinchaudhary** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/81626. [See changes here.](https://github.com/ambrinchaudhary/liferay-portal/compare/6db5e22~13...6db5e22) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
