### PR TITLE
LPS-67757 Stacking the bookmarks container on phones and tablets

### PR DESCRIPTION
**Pull request by 4lejandrito**

### CODE REVIEW

**Comment by 4lejandrito** [comment]
Forwarding to @ambrinchaudhary: https://github.com/ambrinchaudhary/liferay-portal/pull/104

**Comment by ambrinchaudhary** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ambrinchaudhary** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/43576. [See changes here.](https://github.com/ambrinchaudhary/liferay-portal/compare/80f84e1~2...80f84e1) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ambrinchaudhary** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/43577. [See changes here.](https://github.com/ambrinchaudhary/liferay-portal/compare/6f7b768~3...6f7b768) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ambrinchaudhary** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/43593. [See changes here.](https://github.com/ambrinchaudhary/liferay-portal/compare/8921f1e~3...8921f1e) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ambrinchaudhary** [comment]
Pull request submitted to https://github.com/sergiogonzalez/liferay-portal/pull/3495. [See changes here.](https://github.com/ambrinchaudhary/liferay-portal/compare/1a97682~3...1a97682) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
