### PR TITLE
LPS-111244 Replace <liferay-ui:input-editor> with <liferay-editor:editor> in knowledge-base-web

### PR DESCRIPTION
**Pull request by mateomustapic**
The goal of this change is to replace liferay-ui:input-editor
(which was deprecated in 7.1.0) with liferay-editor:editor in knowledge-base-web.
The behaviour and looks of editor after these changes should be the same, also the build should be successful after deploy of new gradle dependency.

### CODE REVIEW

**Comment by mateomustapic** [comment]
ci:test:sf

**Comment by mateomustapic** [comment]
ci:test:stable

**Comment by mateomustapic** [comment]
ci:test:relevant

**Comment by ambrinchaudhary** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ambrinchaudhary** [comment]
Pull request submitted to https://github.com/ambrinchaudhary/liferay-portal/pull/332. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ambrinchaudhary** [comment]
Pull request submitted to https://github.com/ambrinchaudhary/liferay-portal/pull/333. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ambrinchaudhary** [comment]
Resend here just to see a clean pull https://github.com/ambrinchaudhary/liferay-portal/pull/333

**Pull request closed without merging**
