### PR TITLE
LPS-108806 wip

### PR DESCRIPTION
**Pull request by robertoDiaz**

### CODE REVIEW

**Comment by ambrinchaudhary** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ambrinchaudhary** [comment]
Just started reviewing :)

**Comment by ambrinchaudhary** [comment]
Pull request submitted to https://github.com/robertoDiaz/liferay-portal/pull/816. [See changes here.](https://github.com/ambrinchaudhary/liferay-portal/compare/a4fa164a07db~3...a4fa164a07db)

**Comment by ambrinchaudhary** [comment]
Pull request submitted to https://github.com/adolfopa/liferay-portal/pull/1286. [See changes here.](https://github.com/ambrinchaudhary/liferay-portal/compare/58ac8954dfba~3...58ac8954dfba)

**Comment by robertoDiaz** [comment]
@ambrinchaudhary 

Mil gracias

**Pull request closed without merging**
