### PR TITLE
LPS-74468 "Get URL" and "WebDAV URL" fields are not selected on iOS on tap

### PR DESCRIPTION
**Pull request by IstvanD**
Hey @ambrinchaudhary 

As per request from https://github.com/robertoDiaz/liferay-portal/pull/598#issuecomment-326559103 I'm sending this pull request to you.

If you're not the reviewer of the DM component, please feel free to forward it to the actual one.

You can find the details and explanation of the solution the the pull https://github.com/robertoDiaz/liferay-portal/pull/598

Thank you!

Best regards,
István

### CODE REVIEW

**Comment by IstvanD** [comment]
Hey @ambrinchaudhary 

I was wondering if you find time to review this pull request.
Because it is a customer reported issue, we intent to backport and release the solution in a fix pack as soon as possible.

Thank you in advance.

Best regards,
István

**Comment by ambrinchaudhary** [comment]
Hey Istvan,
I see you closed this PR. Did you send it to someone else? 
I'm not at office these days and was going to send it to someone.

**Comment by IstvanD** [comment]
Hey Ambrin,

I've closed the pull because it turned out that there were some cases where it didn't fixed the issue.
To whom should I sent the pull once it is ready?

Thank you,
István

**Comment by ambrinchaudhary** [comment]
Send it to @p2kmgcl please. Thank you Istvan

**Pull request closed without merging**
