### PR TITLE
LPS-110169 Redirections: validate url

### PR DESCRIPTION
**Pull request by ambrinchaudhary**

### CODE REVIEW

**Comment by ambrinchaudhary** [comment]
ci:forward

**Comment by ambrinchaudhary** [comment]
Hi @john-co,

do you have any idea why CI is failing at this pull? Seems something related with the tests, but they are working fine in local, event that failing task "packageRunTest" passes... so I have no idea where to look... 

Thanks for your time!

**Comment by ambrinchaudhary** [comment]
ci:forward

**Comment by john-co** [comment]
Just started reviewing :)

**Comment by john-co** [comment]
looks like the test is failing on
```
     [exec] > Task :apps:redirect:redirect-web:packageRunTest FAILED
     [exec] FAIL test/DestinationURLInput.js
     [exec]   ??? Test suite failed to run
     [exec] 
     [exec]     Cannot find module '../src/main/resources/META-INF/resources/js/DestinationURLInput' from 'DestinationURLInput.js'
     [exec] 
     [exec]       16 | import React from 'react';
     [exec]       17 | 
     [exec]     > 18 | import DestinationURLInput from '../src/main/resources/META-INF/resources/js/DestinationURLInput';
     [exec]          | ^
     [exec]       19 | 
     [exec]       20 | const defaultProps = {
     [exec]       21 | 	namespace: '_portlet_namespace_',
     [exec] 
     [exec]       at Resolver.resolveModule (../../../node_modules/jest-resolve/build/index.js:276:11)
     [exec]       at Object.<anonymous> (test/DestinationURLInput.js:18:1)
     [exec] 
     [exec] Test Suites: 1 failed, 1 total
```

fetching from this branch and testing locally with the `rename test file` commit passes.

**Comment by john-co** [comment]
the js-unit test failures are now ignored at head, rerunning tests

**Comment by john-co** [comment]
ci:test:relevant

**Comment by ambrinchaudhary** [comment]
ci:forward

**Comment by ambrinchaudhary** [comment]
> looks like the test is failing on
> 
> ```
>      [exec] > Task :apps:redirect:redirect-web:packageRunTest FAILED
>      [exec] FAIL test/DestinationURLInput.js
>      [exec]   ??? Test suite failed to run
>      [exec] 
>      [exec]     Cannot find module '../src/main/resources/META-INF/resources/js/DestinationURLInput' from 'DestinationURLInput.js'
>      [exec] 
>      [exec]       16 | import React from 'react';
>      [exec]       17 | 
>      [exec]     > 18 | import DestinationURLInput from '../src/main/resources/META-INF/resources/js/DestinationURLInput';
>      [exec]          | ^
>      [exec]       19 | 
>      [exec]       20 | const defaultProps = {
>      [exec]       21 | 	namespace: '_portlet_namespace_',
>      [exec] 
>      [exec]       at Resolver.resolveModule (../../../node_modules/jest-resolve/build/index.js:276:11)
>      [exec]       at Object.<anonymous> (test/DestinationURLInput.js:18:1)
>      [exec] 
>      [exec] Test Suites: 1 failed, 1 total
> ```
> 
> fetching from this branch and testing locally with the `rename test file` commit passes.

Thanks for looking into it @john-co, trying again all the test passes...

**Comment by ambrinchaudhary** [comment]
ci:test:relevant

**Comment by ambrinchaudhary** [comment]
ci:forward

**Pull request closed without merging**
