### PR TITLE
LPS-111232 Replace <liferay-ui:input-editor> with <liferay-editor:edittor> in  blogs-web

### PR DESCRIPTION
**Pull request by julien**
The goal of this change is to replace `<liferay-ui:input-editor>`
(which was deprecated in 7.1.0) with `<liferay-editor:editor>`.

A previous Jira ticket (https://issues.liferay.com/browse/LPS-110008)
and pull request (#320) are currently in review and change the same files,
so the commits on the previous PR (#320) have been cherry picked on this
branch to avoid confusion.

### CODE REVIEW

**Comment by julien** [comment]
ci:test:sf

**Comment by julien** [comment]
ci:test:stable

**Comment by julien** [comment]
ci:test:relevant

**Comment by julien** [comment]
ci:test:stable

**Comment by julien** [comment]
ci:test:relevant

**Comment by ambrinchaudhary** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ambrinchaudhary** [comment]
Pull request submitted to https://github.com/austinchiang/liferay-portal/pull/738. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
