### PR TITLE
LPS-110369 Replace AlloyEditor in Title field in Knowledge Base Articles

### PR DESCRIPTION
**Pull request by julien**

### CODE REVIEW

**Comment by julien** [comment]
ci:test:sf

**Comment by julien** [comment]
ci:test:stable

**Comment by julien** [comment]
ci:test:sf

**Comment by ambrinchaudhary** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ambrinchaudhary** [comment]
Pull request submitted to https://github.com/4lejandrito/liferay-portal/pull/397. [See changes here.](https://github.com/ambrinchaudhary/liferay-portal/compare/03e5014~2...03e5014) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
